services:
  - type: web
    name: cineverse-backend
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: GEMINI_API_KEY
        sync: false
